<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $vehicles = [
            [
                "registration_no" => "KAA 123A",
                "make" => "Toyota",
                "model" => "Land Cruiser",
                "chassis_no" => "JTEHT05JX00000001",
                "engine_no" => "1HD-FTE0000001",
                "tag_number" => "TAG001",
                "pv_number" => "PV001",
                "vehicle_type" => "SUV",
                "capacity" => "7 passengers",
                "fuel_type" => "Diesel",
                "fuel_tank_capacity" => 90,
                "date_of_purchase" => Carbon::parse("2023-01-15"),
                "year_of_purchase" => 2023,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 4500000.0,
                "original_location" => "Nairobi HQ",
                "current_location" => "Nairobi HQ",
                "current_mileage" => 15000,
                "status" => "Available",
                "responsible_officer" => "Jane Smith",
                "asset_condition" => "Excellent",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(8),
                "road_license_expiry" => Carbon::now()->addMonths(10),
                "next_service_due" => Carbon::now()->addMonths(2),
                "depreciation_rate" => 15.0,
                "notes" => "Primary executive vehicle for official duties",
            ],
            [
                "registration_no" => "KAA 456B",
                "make" => "Mitsubishi",
                "model" => "L200",
                "chassis_no" => "MMBJNKB70CD000001",
                "engine_no" => "4D56-0000001",
                "tag_number" => "TAG002",
                "pv_number" => "PV002",
                "vehicle_type" => "Pickup Truck",
                "capacity" => "2 tons",
                "fuel_type" => "Diesel",
                "fuel_tank_capacity" => 75,
                "date_of_purchase" => Carbon::parse("2023-02-20"),
                "year_of_purchase" => 2023,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 3200000.0,
                "original_location" => "Mombasa Office",
                "current_location" => "Mombasa Office",
                "current_mileage" => 25000,
                "status" => "In Maintenance",
                "responsible_officer" => "Mark Thompson",
                "asset_condition" => "Good",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(6),
                "road_license_expiry" => Carbon::now()->addMonths(8),
                "next_service_due" => Carbon::now()->subDays(5),
                "depreciation_rate" => 20.0,
                "notes" => "Utility vehicle for cargo transport",
            ],
            [
                "registration_no" => "KAA 789C",
                "make" => "Toyota",
                "model" => "Hiace",
                "chassis_no" => "LHGDM81H00000001",
                "engine_no" => "2KD-FTV0000001",
                "tag_number" => "TAG003",
                "pv_number" => "PV003",
                "vehicle_type" => "Van",
                "capacity" => "14 passengers",
                "fuel_type" => "Diesel",
                "fuel_tank_capacity" => 70,
                "date_of_purchase" => Carbon::parse("2023-03-10"),
                "year_of_purchase" => 2023,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 2800000.0,
                "original_location" => "Kisumu Branch",
                "current_location" => "Kisumu Branch",
                "current_mileage" => 18000,
                "status" => "On Trip",
                "responsible_officer" => "Sarah Davis",
                "asset_condition" => "Good",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(9),
                "road_license_expiry" => Carbon::now()->addMonths(11),
                "next_service_due" => Carbon::now()->addMonths(1),
                "depreciation_rate" => 18.0,
                "notes" => "Staff transport vehicle for group movements",
            ],
            [
                "registration_no" => "KAA 012D",
                "make" => "Toyota",
                "model" => "Corolla",
                "chassis_no" => "2T1BURHE00000001",
                "engine_no" => "2ZR-FE0000001",
                "tag_number" => "TAG004",
                "pv_number" => "PV004",
                "vehicle_type" => "Sedan",
                "capacity" => "5 passengers",
                "fuel_type" => "Petrol",
                "fuel_tank_capacity" => 50,
                "date_of_purchase" => Carbon::parse("2023-04-05"),
                "year_of_purchase" => 2023,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 2200000.0,
                "original_location" => "Eldoret Office",
                "current_location" => "Eldoret Office",
                "current_mileage" => 12000,
                "status" => "Available",
                "responsible_officer" => "Jane Smith",
                "asset_condition" => "Excellent",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(7),
                "road_license_expiry" => Carbon::now()->addMonths(9),
                "next_service_due" => Carbon::now()->addMonths(3),
                "depreciation_rate" => 25.0,
                "notes" => "Compact vehicle for city operations",
            ],
            [
                "registration_no" => "KAA 345E",
                "make" => "Isuzu",
                "model" => "D-Max",
                "chassis_no" => "MPATFS85J00000001",
                "engine_no" => "4JJ1-TC0000001",
                "tag_number" => "TAG005",
                "pv_number" => "PV005",
                "vehicle_type" => "Pickup Truck",
                "capacity" => "1.5 tons",
                "fuel_type" => "Diesel",
                "fuel_tank_capacity" => 76,
                "date_of_purchase" => Carbon::parse("2022-05-15"),
                "year_of_purchase" => 2022,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 3500000.0,
                "original_location" => "Nakuru Office",
                "current_location" => "Nakuru Office",
                "current_mileage" => 45000,
                "status" => "Available",
                "responsible_officer" => "Mark Thompson",
                "asset_condition" => "Fair",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(4),
                "road_license_expiry" => Carbon::now()->addMonths(6),
                "next_service_due" => Carbon::now()->addWeeks(2),
                "depreciation_rate" => 20.0,
                "notes" => "Heavy-duty pickup for equipment transport",
            ],
            [
                "registration_no" => "KAB 678F",
                "make" => "Nissan",
                "model" => "Patrol",
                "chassis_no" => "JN1TBNY61U0000001",
                "engine_no" => "TB48DE0000001",
                "tag_number" => "TAG006",
                "pv_number" => "PV006",
                "vehicle_type" => "SUV",
                "capacity" => "8 passengers",
                "fuel_type" => "Petrol",
                "fuel_tank_capacity" => 95,
                "date_of_purchase" => Carbon::parse("2022-08-20"),
                "year_of_purchase" => 2022,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 5200000.0,
                "original_location" => "Garissa Office",
                "current_location" => "Garissa Office",
                "current_mileage" => 38000,
                "status" => "Available",
                "responsible_officer" => "Sarah Davis",
                "asset_condition" => "Good",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(5),
                "road_license_expiry" => Carbon::now()->addMonths(7),
                "next_service_due" => Carbon::now()->addMonths(1),
                "depreciation_rate" => 18.0,
                "notes" => "All-terrain vehicle for remote area operations",
            ],
            [
                "registration_no" => "KAC 901G",
                "make" => "Ford",
                "model" => "Transit",
                "chassis_no" => "WF0XXXTTGXHW000001",
                "engine_no" => "TDCI0000001",
                "tag_number" => "TAG007",
                "pv_number" => "PV007",
                "vehicle_type" => "Van",
                "capacity" => "12 passengers",
                "fuel_type" => "Diesel",
                "fuel_tank_capacity" => 80,
                "date_of_purchase" => Carbon::parse("2022-11-12"),
                "year_of_purchase" => 2022,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 3800000.0,
                "original_location" => "Machakos Office",
                "current_location" => "Machakos Office",
                "current_mileage" => 32000,
                "status" => "Available",
                "responsible_officer" => "Jane Smith",
                "asset_condition" => "Good",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(6),
                "road_license_expiry" => Carbon::now()->addMonths(8),
                "next_service_due" => Carbon::now()->addMonths(2),
                "depreciation_rate" => 22.0,
                "notes" => "Medium capacity transport for official events",
            ],
            [
                "registration_no" => "KAD 234H",
                "make" => "Toyota",
                "model" => "Prado",
                "chassis_no" => "JTEBX3FJ000000001",
                "engine_no" => "2TR-FE0000001",
                "tag_number" => "TAG008",
                "pv_number" => "PV008",
                "vehicle_type" => "SUV",
                "capacity" => "7 passengers",
                "fuel_type" => "Petrol",
                "fuel_tank_capacity" => 87,
                "date_of_purchase" => Carbon::parse("2021-09-18"),
                "year_of_purchase" => 2021,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 6200000.0,
                "original_location" => "Nairobi HQ",
                "current_location" => "Nairobi HQ",
                "current_mileage" => 65000,
                "status" => "Available",
                "responsible_officer" => "Mark Thompson",
                "asset_condition" => "Good",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(3),
                "road_license_expiry" => Carbon::now()->addMonths(5),
                "next_service_due" => Carbon::now()->addWeeks(3),
                "depreciation_rate" => 16.0,
                "notes" => "Executive vehicle for senior management",
            ],
            [
                "registration_no" => "KAE 567I",
                "make" => "Mitsubishi",
                "model" => "Canter",
                "chassis_no" => "MK619JPA4WH000001",
                "engine_no" => "4M50T0000001",
                "tag_number" => "TAG009",
                "pv_number" => "PV009",
                "vehicle_type" => "Truck",
                "capacity" => "5 tons",
                "fuel_type" => "Diesel",
                "fuel_tank_capacity" => 100,
                "date_of_purchase" => Carbon::parse("2021-12-03"),
                "year_of_purchase" => 2021,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 4800000.0,
                "original_location" => "Thika Depot",
                "current_location" => "Thika Depot",
                "current_mileage" => 78000,
                "status" => "Available",
                "responsible_officer" => "Sarah Davis",
                "asset_condition" => "Fair",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addMonths(2),
                "road_license_expiry" => Carbon::now()->addMonths(4),
                "next_service_due" => Carbon::now()->addDays(10),
                "depreciation_rate" => 24.0,
                "notes" => "Heavy cargo transport vehicle",
            ],
            [
                "registration_no" => "KAF 890J",
                "make" => "Honda",
                "model" => "Civic",
                "chassis_no" => "2HGFC2F53MH000001",
                "engine_no" => "R18A0000001",
                "tag_number" => "TAG010",
                "pv_number" => "PV010",
                "vehicle_type" => "Sedan",
                "capacity" => "5 passengers",
                "fuel_type" => "Petrol",
                "fuel_tank_capacity" => 47,
                "date_of_purchase" => Carbon::parse("2020-06-25"),
                "year_of_purchase" => 2020,
                "financed_by" => "Government Fleet",
                "funded_by" => "Government",
                "amount" => 2800000.0,
                "original_location" => "Meru Office",
                "current_location" => "Meru Office",
                "current_mileage" => 95000,
                "status" => "In Maintenance",
                "responsible_officer" => "Jane Smith",
                "asset_condition" => "Fair",
                "has_logbook" => true,
                "insurance_expiry" => Carbon::now()->addDays(30),
                "road_license_expiry" => Carbon::now()->addMonths(2),
                "next_service_due" => Carbon::now()->subWeeks(1),
                "depreciation_rate" => 30.0,
                "notes" => "Fuel-efficient vehicle for daily operations",
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            // Calculate depreciation values
            $yearsOld = Carbon::now()->diffInYears(
                $vehicleData["date_of_purchase"]
            );
            $annualDepreciation =
                $vehicleData["amount"] *
                ($vehicleData["depreciation_rate"] / 100);
            $accumulatedDepreciation = $annualDepreciation * $yearsOld;
            $netBookValue = max(
                0,
                $vehicleData["amount"] - $accumulatedDepreciation
            );

            $vehicleData["annual_depreciation"] = $annualDepreciation;
            $vehicleData["accumulated_depreciation"] = $accumulatedDepreciation;
            $vehicleData["net_book_value"] = $netBookValue;

            Vehicle::create($vehicleData);
        }

        $this->command->info("Vehicles created successfully!");
        $this->command->info("Total vehicles created: " . Vehicle::count());
        $this->command->info(
            "Available vehicles: " .
                Vehicle::where("status", "Available")->count()
        );
        $this->command->info(
            "Vehicles in maintenance: " .
                Vehicle::where("status", "In Maintenance")->count()
        );
        $this->command->info(
            "Vehicles on trip: " . Vehicle::where("status", "On Trip")->count()
        );
    }
}
